# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 23:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_expired', models.DateTimeField(default=datetime.datetime.now, verbose_name='deadline date')),
                ('is_complete', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='finished')),
                ('name', models.CharField(max_length=45)),
                ('in_progtess', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
