# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
