# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_task_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='in_progtess',
            new_name='in_progress',
        ),
    ]
